### PR TITLE
Update Xamarin.Forms to v4.3

### PR DESCRIPTION
**Pull request by bbenetskyy**
Please, pay attention to `lib` project, I can't compile this one by local problems but it should work. Also after this update, you may push a new version of NuGet

### CODE REVIEW

**Comment by mariusmuntean** [comment]
Hi,

You need to update MSBuild.Sdk.extras to the latest version (2.0.54 as of now). To do so, manually change the lib's .csproj file (lines 1 and 72).
Then it builds again. Or you can allow me to make the changes to your PR (here's how to do it https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

To me this smells like the package has changes and either line 1 or 72 is not necessary anymore, but I don't have the time right now to look into it.

Other than that the PR seems fine.

**Comment by mariusmuntean** [comment]
By the way, the FormsRevealer NuGet package declares a dependency on Xamarin.Forms 3.6 and newer.
This means there is no need to increase the Xamarin.Forms version in the lib.

Did you experience any issues due to the referenced Xamarin.Forms version? If not, I would keep it as 3.6+ to achieve maximum compatibility.

**Comment by bbenetskyy** [comment]
I'm out of office for couple days. I'm enable edit for maintainers, you may charge it 😜 thanks

**Comment by bbenetskyy** [comment]
@mariusmuntean just update MSBuild SDK to the latest (2.0.54) version. And according to your question - no I didn't see any issues with newer Xamarin.Forms

**Pull request merged**
